config/routes.rb
Rails.application.routes.draw do
  resources :rent_comparators
  resources :airbnb_host_places
  root 'rent_comparators#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/airbnb_host_place.rb
class AirbnbHostPlace < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true

  def self.compare(address, long_term_rental_income)
    airbnb_place = find_near_location address
    message = ""
    if airbnb_place.present?
      if airbnb_place.price > long_term_rental_income
        message = "Profit: #{airbnb_place.price - long_term_rental_income}, comparing to monthly rental"
      else
        message = "Loss: #{long_term_rental_income - airbnb_place.price}, comparing to long term monthly rental"
      end
    else
      message = "No Airbnb Host Places found."
    end
  end

  def self.find_near_location address
    #Searching entered address in AirbnbHostPlace addresses within one mile
    near(address, 1).first
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/airbnb_host_places_controller.rb
class AirbnbHostPlacesController < ApplicationController
  before_action :set_airbnb_host_place, only: [:show, :edit, :update, :destroy]

  # GET /airbnb_host_places
  # GET /airbnb_host_places.json
  def index
    @airbnb_host_places = AirbnbHostPlace.all
  end

  # GET /airbnb_host_places/1
  # GET /airbnb_host_places/1.json
  def show
  end

  # GET /airbnb_host_places/new
  def new
    @airbnb_host_place = AirbnbHostPlace.new
  end

  # GET /airbnb_host_places/1/edit
  def edit
  end

  # POST /airbnb_host_places
  # POST /airbnb_host_places.json
  def create
    @airbnb_host_place = AirbnbHostPlace.new(airbnb_host_place_params)

    respond_to do |format|
      if @airbnb_host_place.save
        format.html { redirect_to @airbnb_host_place, notice: 'Airbnb host place was successfully created.' }
        format.json { render :show, status: :created, location: @airbnb_host_place }
      else
        format.html { render :new }
        format.json { render json: @airbnb_host_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /airbnb_host_places/1
  # PATCH/PUT /airbnb_host_places/1.json
  def update
    respond_to do |format|
      if @airbnb_host_place.update(airbnb_host_place_params)
        format.html { redirect_to @airbnb_host_place, notice: 'Airbnb host place was successfully updated.' }
        format.json { render :show, status: :ok, location: @airbnb_host_place }
      else
        format.html { render :edit }
        format.json { render json: @airbnb_host_place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /airbnb_host_places/1
  # DELETE /airbnb_host_places/1.json
  def destroy
    @airbnb_host_place.destroy
    respond_to do |format|
      format.html { redirect_to airbnb_host_places_url, notice: 'Airbnb host place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_airbnb_host_place
      @airbnb_host_place = AirbnbHostPlace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def airbnb_host_place_params
      params.require(:airbnb_host_place).permit(:name, :address, :price, :place_type, :no_of_guests, :latitude, :longitude)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/rent_comparators_controller.rb
class RentComparatorsController < ApplicationController
  before_action :set_rent_comparator, only: [:show, :edit, :update, :destroy]

  # GET /rent_comparators
  # GET /rent_comparators.json
  def index
    if params[:address].present? && params[:long_term_rental_income].present?
      @result = AirbnbHostPlace.compare(params[:address], params[:long_term_rental_income].to_d)
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_comparator_params
      params.require(:rent_comparator).permit(:address, :long_term_rental_income)
    end
end

app/helpers/airbnb_host_places_helper.rb
module AirbnbHostPlacesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rent_comparators_helper.rb
module RentComparatorsHelper
end

app/views/airbnb_host_places/_form.html.erb
<%= form_with(model: airbnb_host_place, local: true) do |form| %>
  <% if airbnb_host_place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(airbnb_host_place.errors.count, "error") %> prohibited this airbnb_host_place from being saved:</h2>

      <ul>
      <% airbnb_host_place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :airbnb_host_place_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, :id => 'geo-input' %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :airbnb_host_place_price %>
  </div>

  <div class="field">
    <%= form.label :place_type %>
    <%= form.text_field :place_type, id: :airbnb_host_place_place_type %>
  </div>

  <div class="field">
    <%= form.label :no_of_guests %>
    <%= form.number_field :no_of_guests, id: :airbnb_host_place_no_of_guests %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/airbnb_host_places/edit.html.erb
<h1>Editing Airbnb Host Place</h1>

<%= render 'form', airbnb_host_place: @airbnb_host_place %>

<%= link_to 'Show', @airbnb_host_place %> |
<%= link_to 'Back', airbnb_host_places_path %>

app/views/airbnb_host_places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Airbnb Host Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Place Type</th>
      <th>No of guests</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @airbnb_host_places.each do |airbnb_host_place| %>
      <tr>
        <td><%= airbnb_host_place.name %></td>
        <td><%= airbnb_host_place.address %></td>
        <td><%= airbnb_host_place.price %></td>
        <td><%= airbnb_host_place.place_type %></td>
        <td><%= airbnb_host_place.no_of_guests %></td>
        <td><%= airbnb_host_place.latitude %></td>
        <td><%= airbnb_host_place.longitude %></td>
        <td><%= link_to 'Show', airbnb_host_place %></td>
        <td><%= link_to 'Edit', edit_airbnb_host_place_path(airbnb_host_place) %></td>
        <td><%= link_to 'Destroy', airbnb_host_place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/airbnb_host_places/new.html.erb
<h1>New Airbnb Host Place</h1>

<%= render 'form', airbnb_host_place: @airbnb_host_place %>

<%= link_to 'Back', airbnb_host_places_path %>

app/views/airbnb_host_places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @airbnb_host_place.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @airbnb_host_place.address %>
</p>

<p>
  <strong>Price:</strong>
  <%= @airbnb_host_place.price %>
</p>

<p>
  <strong>Place Type:</strong>
  <%= @airbnb_host_place.place_type %>
</p>

<p>
  <strong>No of guests:</strong>
  <%= @airbnb_host_place.no_of_guests %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @airbnb_host_place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @airbnb_host_place.longitude %>
</p>

<%= link_to 'Edit', edit_airbnb_host_place_path(@airbnb_host_place) %> |
<%= link_to 'Back', airbnb_host_places_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbRental</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;key=AIzaSyDRxpYSfeVzq75bkQQYdxGUhhAREUgFcaw&libraries=places"></script>
    <script src="jquery.geocomplete.js"></script>
  </body>
</html>

app/views/rent_comparators/index.html.erb
<div class="centered">
  <h1>Airbnb Rental Comparator</h1>
  <%= form_tag rent_comparators_path, :method => :get do %>
      <p>
        <%= label_tag(:q, "Address:") %>
        <%= text_field_tag :address, params[:address],:id => 'geo-input' %>

        <%= label_tag(:q, "Long Term Rental Income Per Month:") %>
        <%= number_field_tag(:long_term_rental_income) %>
        <%= label_tag(:q,"")%>
        <%= submit_tag "Compare with Airbnb Rental", :name => nil %>
      </p>
  <% end %>

  <% if @result.present? %>
      <%= @result %>
  <% end %>
</div>

app/views/rent_comparators/new.html.erb
<%= @result %>

<%= link_to 'Compare With New Address', rent_comparators_path %>